version: 2

builds:
  - main: .
    binary: selfstack
    ldflags:
      - -s -w -X github.com/selfstack/selfstack/cmd.Version={{ .Version }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz

checksum:
  name_template: checksums.txt

release:
  github:
    owner: Avanderheyde
    name: self-stack
